"""
report.py
---------
Generates human-readable scan reports in TXT, HTML, and PDF formats.
"""

import os
import html as html_lib

from scanner import risk_label

SEVERITY_ICON = {
    "good": "✅",
    "low": "ℹ️",
    "medium": "⚠️",
    "high": "❌",
    "critical": "🛑",
}


def _safe_filename(url: str) -> str:
    name = url.replace("https://", "").replace("http://", "")
    name = "".join(c if c.isalnum() or c in "._-" else "_" for c in name)
    return name.strip("_") or "scan"


def build_txt(result: dict) -> str:
    lines = []
    lines.append("=" * 60)
    lines.append("  PERSONAL SECURITY SCANNER — SCAN REPORT")
    lines.append("=" * 60)
    lines.append(f"Website     : {result.get('url')}")
    lines.append(f"Date        : {result.get('date')}  {result.get('time')}")
    lines.append(f"Scan Time   : {result.get('duration_seconds')}s")
    lines.append(f"Risk Score  : {result.get('risk_score')}/100 ({risk_label(result.get('risk_score', 0))})")
    lines.append("")
    lines.append("-" * 60)
    lines.append("FINDINGS")
    lines.append("-" * 60)
    for f in result.get("findings", []):
        icon = SEVERITY_ICON.get(f["severity"], "")
        lines.append(f"{f['title']}")
        lines.append(f"   Why it matters : {f['why']}")
        lines.append(f"   Recommendation : {f['fix']}")
        lines.append("")

    lines.append("-" * 60)
    lines.append("RAW CHECK DATA")
    lines.append("-" * 60)

    ssl_info = result.get("ssl", {})
    lines.append("[SSL / TLS]")
    lines.append(f"  HTTPS Enabled   : {result.get('https_enabled')}")
    lines.append(f"  Issuer          : {ssl_info.get('issuer')}")
    lines.append(f"  Expires On      : {ssl_info.get('expires_on')}")
    lines.append(f"  Valid           : {ssl_info.get('valid')}")
    lines.append(f"  Expired         : {ssl_info.get('expired')}")
    lines.append(f"  TLS Version     : {ssl_info.get('tls_version')}")
    lines.append("")

    lines.append("[Security Headers]")
    for h, v in result.get("security_headers", {}).items():
        lines.append(f"  {h:32s}: {'Present' if v else 'Missing'}")
    lines.append("")

    lines.append("[Server Info]")
    for h, v in result.get("server_info", {}).items():
        lines.append(f"  {h:15s}: {v or 'Not disclosed'}")
    lines.append("")

    lines.append("[robots.txt / sitemap.xml]")
    lines.append(f"  robots.txt exists  : {result.get('robots', {}).get('exists')}")
    lines.append(f"  sitemap.xml exists : {result.get('sitemap', {}).get('exists')}")
    lines.append("")

    lines.append("[Exposed File Paths]")
    for f in result.get("exposed_files", []):
        lines.append(f"  {f['path']:15s}: {'ACCESSIBLE' if f['accessible'] else 'Not accessible'}")
    lines.append("")

    lines.append("[HTTP Methods]")
    for m, allowed in result.get("http_methods", {}).items():
        lines.append(f"  {m:8s}: {'Allowed' if allowed else 'Not allowed'}")
    lines.append("")

    lines.append("[Cookies]")
    for c in result.get("cookies", []):
        lines.append(f"  {c['name']}: Secure={c['secure']} HttpOnly={c['httponly']} SameSite={c['samesite']}")
    lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by Personal Security Scanner — passive, educational scan only.")
    return "\n".join(lines)


def build_html(result: dict) -> str:
    findings_html = ""
    for f in result.get("findings", []):
        icon = SEVERITY_ICON.get(f["severity"], "")
        findings_html += f"""
        <div class="finding {f['severity']}">
            <h3>{html_lib.escape(f['title'])}</h3>
            <p><strong>Why it matters:</strong> {html_lib.escape(f['why'])}</p>
            <p><strong>Recommendation:</strong> {html_lib.escape(f['fix'])}</p>
        </div>"""

    headers_rows = "".join(
        f"<tr><td>{html_lib.escape(h)}</td><td>{'✅ Present' if v else '❌ Missing'}</td></tr>"
        for h, v in result.get("security_headers", {}).items()
    )
    server_rows = "".join(
        f"<tr><td>{html_lib.escape(h)}</td><td>{html_lib.escape(str(v)) if v else 'Not disclosed'}</td></tr>"
        for h, v in result.get("server_info", {}).items()
    )
    files_rows = "".join(
        f"<tr><td>{html_lib.escape(f['path'])}</td><td>{'🛑 Accessible' if f['accessible'] else '✅ Not accessible'}</td></tr>"
        for f in result.get("exposed_files", [])
    )
    methods_rows = "".join(
        f"<tr><td>{m}</td><td>{'Allowed' if allowed else 'Not allowed'}</td></tr>"
        for m, allowed in result.get("http_methods", {}).items()
    )

    ssl_info = result.get("ssl", {})
    score = result.get("risk_score", 0)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Security Scan Report — {html_lib.escape(result.get('url', ''))}</title>
<style>
    body {{ font-family: 'Segoe UI', Arial, sans-serif; background:#0f1115; color:#eef1f6; margin:0; padding:40px; }}
    .container {{ max-width: 900px; margin: 0 auto; }}
    .top-card {{ background: linear-gradient(135deg,#2F6BFF,#7B5CFF); border-radius:16px; padding:28px; margin-bottom:24px; }}
    .top-card h1 {{ margin:0 0 8px 0; font-size:24px; }}
    .score {{ font-size:42px; font-weight:bold; }}
    table {{ width:100%; border-collapse: collapse; margin-bottom: 24px; }}
    td, th {{ padding: 8px 12px; border-bottom: 1px solid #2a2e38; text-align:left; }}
    h2 {{ border-bottom: 2px solid #2F6BFF; padding-bottom:6px; }}
    .finding {{ background:#1b1e25; border-left:4px solid #888; border-radius:8px; padding:14px 18px; margin-bottom:12px; }}
    .finding.critical, .finding.high {{ border-left-color:#E5484D; }}
    .finding.medium {{ border-left-color:#E8A400; }}
    .finding.low {{ border-left-color:#8FB3D9; }}
    .finding.good {{ border-left-color:#1FAA59; }}
    footer {{ color:#7c7c86; font-size:12px; margin-top:30px; text-align:center; }}
</style>
</head>
<body>
<div class="container">
    <div class="top-card">
        <h1>{html_lib.escape(result.get('url', ''))}</h1>
        <div>Scanned on {html_lib.escape(str(result.get('date','')))} at {html_lib.escape(str(result.get('time','')))} ({result.get('duration_seconds')}s)</div>
        <div class="score">{score}/100 — {risk_label(score)}</div>
    </div>

    <h2>Findings & Recommendations</h2>
    {findings_html}

    <h2>SSL / TLS</h2>
    <table>
        <tr><td>HTTPS Enabled</td><td>{result.get('https_enabled')}</td></tr>
        <tr><td>Issuer</td><td>{html_lib.escape(str(ssl_info.get('issuer')))}</td></tr>
        <tr><td>Expires On</td><td>{html_lib.escape(str(ssl_info.get('expires_on')))}</td></tr>
        <tr><td>Valid</td><td>{ssl_info.get('valid')}</td></tr>
        <tr><td>TLS Version</td><td>{html_lib.escape(str(ssl_info.get('tls_version')))}</td></tr>
    </table>

    <h2>Security Headers</h2>
    <table>{headers_rows}</table>

    <h2>Server Information</h2>
    <table>{server_rows}</table>

    <h2>Exposed File Paths</h2>
    <table>{files_rows}</table>

    <h2>HTTP Methods</h2>
    <table>{methods_rows}</table>

    <footer>Generated by Personal Security Scanner — a passive, educational scan of the site you provided. No exploitation performed.</footer>
</div>
</body>
</html>"""


def save_txt(result: dict, folder: str) -> str:
    os.makedirs(folder, exist_ok=True)
    filename = f"{_safe_filename(result['url'])}_{result['date']}_{result['time'].replace(':', '-')}.txt"
    path = os.path.join(folder, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(build_txt(result))
    return path


def save_html(result: dict, folder: str) -> str:
    os.makedirs(folder, exist_ok=True)
    filename = f"{_safe_filename(result['url'])}_{result['date']}_{result['time'].replace(':', '-')}.html"
    path = os.path.join(folder, filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(build_html(result))
    return path


def save_pdf(result: dict, folder: str) -> str:
    """Generate a PDF report using reportlab. Falls back gracefully if
    reportlab isn't installed by raising a clear error the UI can display."""
    try:
        from reportlab.lib.pagesizes import LETTER
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        )
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    except ImportError as e:
        raise RuntimeError(
            "PDF export requires the 'reportlab' package. Install it with: pip install reportlab"
        ) from e

    os.makedirs(folder, exist_ok=True)
    filename = f"{_safe_filename(result['url'])}_{result['date']}_{result['time'].replace(':', '-')}.pdf"
    path = os.path.join(folder, filename)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleBig", parent=styles["Title"], fontSize=20, spaceAfter=6)
    section_style = ParagraphStyle("Section", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6)
    body_style = styles["BodyText"]

    doc = SimpleDocTemplate(path, pagesize=LETTER, topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    story = []

    story.append(Paragraph("Personal Security Scanner — Report", title_style))
    story.append(Paragraph(f"Website: {result.get('url')}", body_style))
    story.append(Paragraph(f"Date: {result.get('date')} {result.get('time')}  |  Scan time: {result.get('duration_seconds')}s", body_style))
    score = result.get("risk_score", 0)
    story.append(Paragraph(f"<b>Risk Score: {score}/100 ({risk_label(score)})</b>", body_style))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Findings & Recommendations", section_style))
    for f in result.get("findings", []):
        story.append(Paragraph(f"<b>{f['title']}</b>", body_style))
        story.append(Paragraph(f"Why it matters: {f['why']}", body_style))
        story.append(Paragraph(f"Recommendation: {f['fix']}", body_style))
        story.append(Spacer(1, 8))

    def add_table(title, rows, headers_row):
        story.append(Paragraph(title, section_style))
        data = [headers_row] + rows
        t = Table(data, hAlign="LEFT", colWidths=[2.5 * inch, 3.5 * inch])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2F6BFF")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(t)

    ssl_info = result.get("ssl", {})
    add_table("SSL / TLS", [
        ["HTTPS Enabled", str(result.get("https_enabled"))],
        ["Issuer", str(ssl_info.get("issuer"))],
        ["Expires On", str(ssl_info.get("expires_on"))],
        ["Valid", str(ssl_info.get("valid"))],
        ["TLS Version", str(ssl_info.get("tls_version"))],
    ], ["Field", "Value"])

    add_table("Security Headers", [
        [h, "Present" if v else "Missing"] for h, v in result.get("security_headers", {}).items()
    ], ["Header", "Status"])

    add_table("Exposed File Paths", [
        [f["path"], "Accessible" if f["accessible"] else "Not accessible"] for f in result.get("exposed_files", [])
    ], ["Path", "Status"])

    doc.build(story)
    return path
