"""
themes.py
---------
Central theme system for Personal Security Scanner.

Every theme is a plain dictionary of colour tokens. UI widgets pull their
colours from the currently active theme dictionary, so switching themes at
runtime is just a matter of swapping the dictionary and re-rendering.
"""

THEMES = {
    "Light": {
        "label": "🌞 Light Theme",
        "mode": "light",
        "bg": "#F4F6F9",
        "bg_secondary": "#FFFFFF",
        "card": "#FFFFFF",
        "card_border": "#E3E7ED",
        "text": "#1B1F27",
        "text_muted": "#6B7280",
        "accent": "#2F6BFF",
        "accent_hover": "#1E52DB",
        "accent_gradient": ("#2F6BFF", "#7B5CFF"),
        "success": "#1FAA59",
        "warning": "#E8A400",
        "danger": "#E5484D",
        "input_bg": "#F0F2F6",
        "progress": "#2F6BFF",
        "sidebar": "#FFFFFF",
        "icon": "#2F6BFF",
        "shadow": "#D6DAE2",
    },
    "Dark": {
        "label": "🌙 Dark Theme",
        "mode": "dark",
        "bg": "#15171C",
        "bg_secondary": "#1B1E25",
        "card": "#1E212A",
        "card_border": "#2A2E38",
        "text": "#EDEFF3",
        "text_muted": "#9AA1AC",
        "accent": "#5C8AFF",
        "accent_hover": "#7DA1FF",
        "accent_gradient": ("#5C8AFF", "#9D7BFF"),
        "success": "#3DD174",
        "warning": "#F2B233",
        "danger": "#FF5C5F",
        "input_bg": "#252932",
        "progress": "#5C8AFF",
        "sidebar": "#1B1E25",
        "icon": "#5C8AFF",
        "shadow": "#0A0B0E",
    },
    "Blue": {
        "label": "💙 Blue Theme",
        "mode": "dark",
        "bg": "#0B1A2B",
        "bg_secondary": "#0F2338",
        "card": "#123049",
        "card_border": "#1B4266",
        "text": "#E7F1FF",
        "text_muted": "#8FB3D9",
        "accent": "#2FA8FF",
        "accent_hover": "#57BBFF",
        "accent_gradient": ("#2FA8FF", "#2FE0FF"),
        "success": "#33D19C",
        "warning": "#FFC24B",
        "danger": "#FF6B6B",
        "input_bg": "#0F2A44",
        "progress": "#2FA8FF",
        "sidebar": "#0F2338",
        "icon": "#2FA8FF",
        "shadow": "#050D16",
    },
    "Green": {
        "label": "💚 Green Theme",
        "mode": "dark",
        "bg": "#0D1B14",
        "bg_secondary": "#112418",
        "card": "#15301F",
        "card_border": "#1E4A2C",
        "text": "#E7FBEF",
        "text_muted": "#8FCBA4",
        "accent": "#2ECC71",
        "accent_hover": "#4FDE8A",
        "accent_gradient": ("#2ECC71", "#8CE05A"),
        "success": "#2ECC71",
        "warning": "#F2C94C",
        "danger": "#EB5757",
        "input_bg": "#12281A",
        "progress": "#2ECC71",
        "sidebar": "#112418",
        "icon": "#2ECC71",
        "shadow": "#060D08",
    },
    "Purple": {
        "label": "💜 Purple Theme",
        "mode": "dark",
        "bg": "#180B29",
        "bg_secondary": "#1F0F35",
        "card": "#291445",
        "card_border": "#3C1E63",
        "text": "#F1E9FF",
        "text_muted": "#B79FE0",
        "accent": "#9B59FF",
        "accent_hover": "#B07CFF",
        "accent_gradient": ("#9B59FF", "#FF6FD8"),
        "success": "#39D98A",
        "warning": "#F2B84B",
        "danger": "#FF5C8A",
        "input_bg": "#22103A",
        "progress": "#9B59FF",
        "sidebar": "#1F0F35",
        "icon": "#9B59FF",
        "shadow": "#0A0512",
    },
    "Midnight": {
        "label": "🖤 Midnight Theme",
        "mode": "dark",
        "bg": "#000000",
        "bg_secondary": "#0A0A0C",
        "card": "#111114",
        "card_border": "#232327",
        "text": "#F2F2F5",
        "text_muted": "#7C7C86",
        "accent": "#00E5A0",
        "accent_hover": "#33F0B5",
        "accent_gradient": ("#00E5A0", "#00B3FF"),
        "success": "#00E5A0",
        "warning": "#FFC857",
        "danger": "#FF4D6D",
        "input_bg": "#161619",
        "progress": "#00E5A0",
        "sidebar": "#0A0A0C",
        "icon": "#00E5A0",
        "shadow": "#000000",
    },
}

THEME_ORDER = ["Light", "Dark", "Blue", "Green", "Purple", "Midnight"]

SEVERITY_COLORS = {
    "good": "success",
    "low": "success",
    "medium": "warning",
    "high": "danger",
    "critical": "danger",
}


def get_theme(name: str) -> dict:
    """Return the theme dict for a given name, defaulting to Dark."""
    return THEMES.get(name, THEMES["Dark"])
